apiVersion: apps/v1
kind: Deployment
metadata:
  name: churros-notella
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: 'kubernetes.io/hostname'
                labelSelector:
                  matchLabels:
                    app: churros-notella
      containers:
        - image: registry.inpt.fr/churros/notella:latest
          imagePullPolicy: IfNotPresent
          name: api
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 60
            httpGet:
              scheme: HTTP
              path: /health
              port: 8080
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1024Mi'
              cpu: '600m'
          env:
            - name: DATABASE_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: churros-postgresql-app
                  key: uri
            - name: DATABASE_URL
              value: $(DATABASE_BASE_URL)?pool_timeout=60
            - name: APP_PACKAGE_ID
              valueFrom:
                configMapKeyRef:
                  key: PUBLIC_APP_PACKAGE_ID
                  name: churros-config
            - name: FIREBASE_SERVICE_ACCOUNT
              valueFrom:
                secretKeyRef:
                  key: FIREBASE_ADMIN_SERVICE_ACCOUNT_KEY
                  name: churros-secrets
            - name: CONTACT_EMAIL
              valueFrom:
                configMapKeyRef:
                  key: PUBLIC_CONTACT_EMAIL
                  name: churros-config
          envFrom:
            - configMapRef:
                name: churros-config
            - configMapRef:
                name: notella-config
            - secretRef:
                name: churros-secrets
