.buildkit:
  image:
    name: moby/buildkit:rootless
    entrypoint: ["sh", "-c"]
  variables:
    BUILDKITD_FLAGS: --oci-worker-no-process-sandbox
  before_script:
    - |
      mkdir -p ~/.docker && cat > ~/.docker/config.json <<EOF
      {
        "auths": {
          "$CI_REGISTRY": {
            "auth": "$(echo -n "$CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD" | base64)"
          }
        }
      }
      EOF

stages:
  - test
  - build

test:
  image: registry.inpt.fr/inp-net/images/go-just:1.23.5-1.39.0
  stage: test
  rules:
    - when: always
  before_script:
    - apk add git npm jq
    - cp -r typescript typescript_original
    - just build
    - just gen_typescript
  script:
    - |
      if [ "$(git tag -l | tail -1)" != "v$(jq -r .version package.json)" ]; then
        echo "Latest tag does not match package.json version, update the typescript package version then commit the changes"
        exit 1
      fi
    - |
      for file in typescript/*.ts; do
        if ! diff -q $file typescript_original/$(basename $file); then
          diff typescript_original/$(basename $file) $file
          echo "Generated file $file is different from original, please run 'just gen_typescript' and commit the changes"
          exit 1
        fi
      done

build-typescript:
  stage: build
  image: node:22-alpine
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+/
  before_script:
    - apk add npm git
  script:
    - just gen_typescript 
    - npm version minor
    

build:
  extends: .buildkit
  stage: build
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+/
      variables:
        DEPLOY: "true"
  script:
    - |
      if [ "$DEPLOY" == "true" ]; then
        export TAG=$(echo $CI_COMMIT_TAG | sed 's/^v//')
      else
        export TAG=latest-$(echo $CI_COMMIT_SHA | cut -c-6)
      fi
    - |
      buildctl-daemonless.sh build \
          --frontend=dockerfile.v0 \
          --local context=. \
          --local dockerfile=. \
          --opt build-arg:TAG=$TAG \
          --output type=image,name=$CI_REGISTRY_IMAGE:v$TAG,push=$DEPLOY
    - |
      if [ "$DEPLOY" == "true"]; then 
        echo "Successfully built and pushed $CI_REGISTRY_IMAGE:v$TAG"
      else
        echo "Successfully built $CI_REGISTRY_IMAGE:v$TAG"
      fi
