.buildkit:
  image:
    name: moby/buildkit:rootless
    entrypoint: ['sh', '-c']
  variables:
    BUILDKITD_FLAGS: --oci-worker-no-process-sandbox
  before_script:
    - mkdir ~/.docker
    - cp $HARBOR_CONFIG_JSON ~/.docker/config.json

deploy:
  extends: .buildkit
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+/
    - when: manual
  script:
    - export TAG=$(echo $CI_COMMIT_TAG)
    - |
      buildctl-daemonless.sh build \
          --frontend=dockerfile.v0 \
          --local context=. \
          --local dockerfile=. \
          --opt build-arg:TAG=$TAG \
          --output type=image,name=$HARBOR_REGISTRY_IMAGE/notella:v$TAG,push=true
    - echo "Successfully built and pushed $HARBOR_REGISTRY_IMAGE/notella:v$TAG"
