openapi: "3.1.1"
info:
  version: 1.0.0
  title: churros/notella
paths:
  /schedule:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ScheduleRequest"
      responses:
        "201":
          description: created
components:
  schemas:
    ScheduleRequest:
      type: object
      required:
        - when
        - resource
        - event
      properties:
        when:
          type: string
          format: date-time
        resource:
          type: string
          x-go-type: notella.ChurrosId
          x-go-type-import: 
            path: git.inpt.fr/churros/notella
            name: notella
        event:
          type: string
          x-go-type: notella.Event
          x-go-type-import:
            path: git.inpt.fr/churros/notella
            name: notella
