# coucou https://github.com/bleemeo/bleemeo-community-edition/pull/4/files :)

commonLabels:
  app: nats

configMapGenerator:
- name: notella-nats-config
  files:
  - nats.conf

secretGenerator:
- name: notella-nats-jetstream-secrets
  literals:
  - JETSTREAM_PASSWORD=jetstream

resources:
- statefulset.yaml
- service.yaml
