apiVersion: v1
kind: Service
metadata:
  name: churros-notella-nats
spec:
  ports:
  - port: 4222
    name: churros-notella-nats-client
  selector:
    app: churros-notella-nats 
  type: LoadBalancer
